### ISSUE TITLE
Number of datasets and ML algorithms, preprocessing methods!

### ISSUE THREAD

**Issue by mbahmani** [udellgroup/lowrank-automl#12]
Hi,
I have a few questions that I could not find them on the paper.
1. How many datasets did you use for meta-learning?
2. How many machine learning algorithms did you use for meta-learning? (it seems 12)
3. and Also regard to preprocessing and ensembling could explain how it works in oboe(Please talk specifically about statistics)? 
That would be very nice if you could mention this type of information.

**Comment by chengrunyang** [comment]
Hi, sorry for the late reply! Please find the details in Section 4 of the [paper](https://people.ece.cornell.edu/cy/papers/tensor-oboe.pdf). Please ping me again if you have further questions.
