### ISSUE TITLE
AutoLearner crashes on Windows

### ISSUE THREAD

**Issue by pwoller** [udellgroup/lowrank-automl#17]
Hello,

I wanted to try the example from the Readme (Python3.8, Windows 10). Unfortunately, an error occurred when running it under Windows:

```python
...

File ~\miniconda3\envs\automl\lib\site-packages\oboe\auto_learner.py:749, in AutoLearner.fit.<locals>.time_limit(seconds)
    747 def signal_handler(signum, frame):
    748     raise TimeoutException("Time limit reached.")
--> 749 signal.signal(signal.SIGALRM, signal_handler)
    750 signal.alarm(seconds)
    751 try:

AttributeError: module 'signal' has no attribute 'SIGALRM'
```

As it looks Windows does not implement that signal (see https://stackoverflow.com/questions/52779920/why-is-signal-sigalrm-not-working-in-python-on-windows)

Maybe you could find a platform independent solution?

**Comment by chengrunyang** [comment]
Ah I see. Sorry, we've only tested our code in Linux and Unix systems, and unfortunately we wouldn't have enough bandwidth to support Windows. You may consider using a virtual machine if that works.
