### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mbahmani** [udellgroup/lowrank-automl#9]
Hello,
Thanks for your nice framework!
I would like to ask when you release documentation for putting this framework in action and more useability!?

**Comment by chengrunyang** [comment]
Hi @mjbahmani , sorry for not releasing it in time! We plan to get it updated by June. Do you need the refined version sooner?

**Comment by mbahmani** [comment]
Thanks for your reply! that would be Ok! If you need someone for documentation or code review! I am here for any help! ;)

**Comment by chengrunyang** [comment]
Sure, thanks!
